### ISSUE TITLE
Raspberry PI 4 support

### ISSUE THREAD

**Issue by Serveurperso** [jperkin/node-rpio#104]
bcm2835.c look too old for rpi4 I try to upgrade from https://www.airspayce.com/mikem/bcm2835/ & rebuild but same problem...

**Comment by KryQ** [comment]
Check my pull request i updated this library to rpi4 and node 12. Feedback appreciated

**Comment by Serveurperso** [comment]
Thanks a lot for your work

**Comment by jperkin** [comment]
I just pushed v1.1.0 which updates bcm2835 to the latest which allegedly supports RPi 4, as well as adding a board id.  Would be curious to know if this now works for you.

**Comment by jacobq** [comment]
@jperkin I just tried using this library for the first time yesterday, and I was able to read and write GPIO pins on an RPi 4 running that latest raspbian. I had to use Node v10.x instead of 12.x though (see https://github.com/jperkin/node-rpio/issues/101)

**Comment by jperkin** [comment]
Great! I'll be addressing the node 12.x issues in a separate fix.
