### ISSUE TITLE
multiple i2c devices

### ISSUE THREAD

**Issue by sonnny** [jperkin/node-rpio#11]
Thank you for an excellent interface to Raspberry PI. Maybe I'm not reading the docs properly but how do you address multiple i2c devices?

Sonny

**Comment by jperkin** [comment]
There's currently no way to address multiple devices simultaneously, and I'm not sure that it's even possible to do so from a hardware perspective.  However, you should be able to issue `i2cSetSlaveAddress()` calls to select the appropriate device prior to each read or write.

If that doesn't work please let me know, I don't have any multi-address i2c devices to test with.
