### ISSUE TITLE
MCP23017 example request

### ISSUE THREAD

**Issue by jas777** [jperkin/node-rpio#120]
Hello, I have a problem with MCP23017 - I've kinda "copied" python example code into JS and it doesn't work. Does anybody have a working example?

**Comment by jperkin** [comment]
I don't have any of these, sorry.

**Comment by sarink** [comment]
@jas777 Did you ever get it to work?
@jperkin Does this lib support using a port expander (or, is there any reason it wouldn't)?

**Comment by jperkin** [comment]
Not directly, it only knows about native pins, but there's no reason why you can't use it to drive one.

**Comment by jas777** [comment]
> @jas777 Did you ever get it to work? @jperkin Does this lib support using a port expander (or, is there any reason it wouldn't)?

I ended up using `i2c-bus`, you can check my implementation at https://github.com/jas777/quassendorf/blob/main/src/mcp/MCP23017.ts
