### ISSUE TITLE
Provide Prebuild binaries

### ISSUE THREAD

**Issue by neophob** [jperkin/node-rpio#130]
I'm working on a Electron app, mainly on OSX but want to run on a RPi (obviously). Anyway by RPi build from my OSX did not work as expected, after some debugging I ended up on https://www.electron.build/multi-platform-build:

If your app has native dependency, it can be compiled only on the target platform unless prebuild is not used.
prebuild is a solution, but most node modules don’t provide prebuilt binaries.

Tbh I'm not really sure what this exactly means - IF prebuild is used "crosscompile" works?

**Comment by jperkin** [comment]
This won't work.  You can use rpio in mock mode to test on macOS, but proper use will require direct access to the hardware on Linux.

**Comment by neophob** [comment]
thanks @jperkin for your feedback. I like the mock feature very much on OSX. 

The intend of this issue is to provide compiled nodejs binaries for the rpi (armv7l) - with prebuild (https://www.npmjs.com/package/prebuild). This would make installing the library easier and it would "just work" for electron as example. What's you view about that?

**Comment by jperkin** [comment]
I don't like it, but there's nothing stopping you from building your own.
