### ISSUE TITLE
is rpio mocking with my orangepi?

### ISSUE THREAD

**Issue by nerkn** [jperkin/node-rpio#135]
Hi, 
Thanks for wonderful documentation. I tried to run on orangepi 4 but warning warned me about mock mode. I wonder if this lib works for RK3399 or code just so specific to run only known models?

**Comment by jperkin** [comment]
It'll do that if it doesn't recognise the model.  I don't have one of those devices so haven't added support for it yet.  I don't know how different it is to the previous models that are supported.

If you wanted to have a go at adding it that'd be great.  First step would be to add the relevant match to `lib/rpio.js` and see if any of the existing banana/orange pinmaps is accurate.
