### ISSUE TITLE
Using more than one SPI device

### ISSUE THREAD

**Issue by briandorey** [jperkin/node-rpio#15]
I am not able to read/write to more than one device using the library, I am using rpio.spiChipSelect(0); within the function to access the first spi device and then rpio.spiChipSelect(1); to access the second chip but this dosnt seem to work. 

Do I need to create separate instances of the rpio object for each SPI device?

**Comment by gertvermeersch** [comment]
Hey Brian,
I'm only using one SPI device but the chipselect doesn't seem to work with me as well. I got it working by addressing the CSN pin manually using the rpio.write method instead before and after communicating over SPI.

**Comment by briandorey** [comment]
gertvermeersch, thank you for the suggestion with the rpio.write, i will try it later today.

**Comment by jperkin** [comment]
Haven't heard anything back on this one for a while so going to close it out.
