### ISSUE TITLE
Bindings.js Error

### ISSUE THREAD

**Issue by plezhh** [jperkin/node-rpio#167]
Hello,

I have an application with two folders, backend and src, with individuals node_modules folder.

If I require the rpio library in backend all works good.

If I try to require it in src, with npm run build && npm start, I get a blank white page, with the following errors in console:

![image](https://user-images.githubusercontent.com/109816878/180659296-300223e9-9e59-41a3-a4ca-140ce32cddf2.png)

Could you help me with some ideas?

Thanks!

**Comment by plhyhc** [comment]
The rpio library is designed to be used on the backend only.  For use with the GPIO pins.  The frontend which loads into a web browser does not have access to a the GPIO pins.  If you want to connect the frontend to the backend, the best way to do this is by an Ajax requests to a backend method that handles the GPIO I/O.

**Comment by plezhh** [comment]
Ohhh, so that's the problem. Thank you very much!
