### ISSUE TITLE
Unknown PWM channel on Pi Model B

### ISSUE THREAD

**Issue by mukulseth** [jperkin/node-rpio#3]
Hi,

I've been trying to run the PWM example from the repo on the RPi Model B and I keep getting the following error --

Unknown PWM channel for pin16 

using mode:physical - I'm sure the pin is correct as I can toggle the value between HIGH/LOW with basic write statements
using package version 0.4.4

**Comment by RobQuistNL** [comment]
Same issue here... Using pigpio i can write to the pins (pigs p 17 |0 - 255| ) and do the same for pin 22 and 24, but when i open them here with GPIO pins i get the message "Unkonwn PWN channel" as well

**Comment by jperkin** [comment]
Only certain pins support PWM.  On 26-pin variants you can only use GPIO18/P12, whereas on the 40-pin variants you can use GPIO12/Pin32, GPIO13/Pin33, GPIO18/Pin12, or GPIO19/Pin35.  There is a sentence to this effect in the README above the example, perhaps one of you can suggest better wording for either the README or the error message to make this more obvious?  Thanks.

**Comment by RobQuistNL** [comment]
Well, the weird thing is that if I use other tools, such as pigpio, it does work as a PWM pin. Or am I missing something? I mean, i can use pigpio to write 0 to 255 to a pin and the MOSFET on that pin works accordingly (powering my ledstrip)

**Comment by jperkin** [comment]
I'm not familiar with that software, but my guess (really the only explanation) is that it's simply doing software PWM, i.e. manually toggling the pins itself to generate PWM output.  My module doesn't support that, at least not natively (you can always implement it yourself with a suitable for loop), but does support hardware PWM using the pins specified, which is much more efficient.

**Comment by jperkin** [comment]
I've added a paragraph attempting to explain this in the README.

**Comment by RobQuistNL** [comment]
Ah right. In that case I guess this can be closed, right? Maybe add a nice to have feature that supports software PWM (didn't even know that was possible, thanks! :+1: ).

Thanks for the quick replies! :)

**Comment by jperkin** [comment]
I'll close this for now, but adding software PWM seems like something I could add support for at some point.  Cheers.

**Comment by jaqua** [comment]
@RobQuistNL How did you solve your pwm-issue? I'm also trying to power a led strip via software pwm...

**Comment by RobQuistNL** [comment]
I think I used middleware and used pigpio, but its been a long time, don't really recall - Sorry!

**Comment by eltoroit** [comment]
Any update on software PWM?
