### ISSUE TITLE
"Unable to determine board revision"

### ISSUE THREAD

**Issue by felixgalindo** [jperkin/node-rpio#48]
Getting "Unable to determine board revision" for CM3 raspberry pi.

**Comment by felixgalindo** [comment]
Hardware	: BCM2835
Revision	: a020a0

**Comment by felixgalindo** [comment]
Added support for Compute Module 3 revision number.

**Comment by jperkin** [comment]
Thanks, I'll take a look at this. Is it expected that most people will use the expansion header module? Adding support should be straight-forward but I'll need to implement a physical pin mapping, so if it's expected that everyone will have the J5 and J6 60-pin headers then I can write a single mapping.

**Comment by jperkin** [comment]
Have committed this as-is for now.  I'd still like to have proper Compute Module support, but this should at least get things working for you out of the box for now.  Thanks!
