### ISSUE TITLE
Mock gpio not read value

### ISSUE THREAD

**Issue by leonardovilarinho** [jperkin/node-rpio#58]
Hi, I have this code:

```
rpio.open(7, rpio.OUTPUT,  rpio.HIGH)
console.log(rpio.read(7))
```

The output always `undefined`, as this problem can resolved?

**Comment by jperkin** [comment]
Yeh, I think it's reasonable that mock mode at least outputs correct values and makes an attempt at tracking what would have happened, I'll look at adding this.

**Comment by usman-10pearls** [comment]
Hi,
Is there any update on this? I am also facing the same issue.

**Comment by jperkin** [comment]
Not yet unfortunately, I haven't had time to maintain this module recently.  I'll see if I can make some time soon to resolve these issues.
