### ISSUE TITLE
Add support for Rasberry Pi A+

### ISSUE THREAD

**Issue by m7r** [jperkin/node-rpio#6]
On a Raspberry Pi A+:
`var rpio = require('rpio');` == `throw "Unable to determine board revision";`

Suggested fix:
add `case 0x12:` after https://github.com/jperkin/node-rpio/blob/master/lib/rpio.js#L79

**Comment by jperkin** [comment]
Thanks!  Fixed in https://github.com/jperkin/node-rpio/commit/41fe8be6bff5088f41f15e36a2631fd7fd8084f5 and 0.6.6 release.

**Comment by JanTheHun** [comment]
There seems to be a new revision again, mine is 0x15

The suggested fix works for me too, i.e:

`case 0x15:`  at line 137

**Comment by jperkin** [comment]
Added in 1ff629585f06d473b9ba467c5349e491303a93ed and pushed as 0.9.8.  Thanks!

**Comment by jperkin** [comment]
Added, thanks!
