### ISSUE TITLE
Has the latest code base in master been deployed to NPM?

### ISSUE THREAD

**Issue by adamreisnz** [jperkin/node-rpio#61]
I'm looking at the code in the latest npm package version 0.19.9 and this contains hardcoded console log's in the `default_read_handler` etc.

But looking in master here this code is not present. Could you push the latest code to a new version on NPM please so we don't get these logs?

**Comment by jperkin** [comment]
Yeh sorry about that, I forgot that npm publishes whatever is in your work area rather than what's in git, and I had code there that hadn't been committed yet.
