### ISSUE TITLE
RPIO not working with new Raspberry PI 3 Model B+

### ISSUE THREAD

**Issue by Uniphix** [jperkin/node-rpio#67]
I get a auto-detect issue where it uses the rasp-model 3 which is fine, however I think they changed how it works as there is now 40 + another 4 down below.   We are using the RGB on pins 9, 11, 13, 15.  However accordingly to their specifications that it looks relativity the same so I am not sure why it is not working.

**Comment by Uniphix** [comment]
Hello I figured out what was wrong, and provided a pull request to help speed the process #68.

I basically ran the command 

`cat /proc/cpuinfo` to get the current Revision of the Raspberry Pi.

**Comment by jperkin** [comment]
Merged in #68, thanks!
