### ISSUE TITLE
With gpiomem=true closing a pin does not remove the poll

### ISSUE THREAD

**Issue by antlai** [jperkin/node-rpio#7]
I may be missing something, but in rpio.js the close(pin) method does 

    if (!rpio_options.gpiomem)
	if (gpiopin in event_pins)
	       rpio.prototype.poll(pin, undefined);

and it should remove the poll regardless of gpiomem

**Comment by jperkin** [comment]
Good catch, thanks! This was a remnant of an earlier version when I didn't think events could be supported by gpiomem.  Fixed in 0.9.6.
